"""empty message

Revision ID: 13accd7b360b
Revises: 25c26353c300
Create Date: 2020-04-25 00:13:32.517696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13accd7b360b'
down_revision = '25c26353c300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('room',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('current_game_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['current_game_id'], ['game.id'], name=op.f('fk_room_current_game_id_game')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room'))
    )
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_current_game_id'), ['current_game_id'], unique=False)

    op.create_table('player',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('current_room_id', sa.String(length=20), nullable=True),
    sa.Column('current_team', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['current_room_id'], ['room.id'], name=op.f('fk_player_current_room_id_room')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player'))
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_current_room_id'), ['current_room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_current_team'), ['current_team'], unique=False)

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('blue_spymaster_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('complete', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ready', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('red_spymaster_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_game_blue_spymaster_id'), ['blue_spymaster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_red_spymaster_id'), ['red_spymaster_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_game_red_spymaster_id_player'), 'player', ['red_spymaster_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_game_blue_spymaster_id_player'), 'player', ['blue_spymaster_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_game_blue_spymaster_id_player'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_game_red_spymaster_id_player'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_game_red_spymaster_id'))
        batch_op.drop_index(batch_op.f('ix_game_blue_spymaster_id'))
        batch_op.drop_column('red_spymaster_id')
        batch_op.drop_column('ready')
        batch_op.drop_column('complete')
        batch_op.drop_column('blue_spymaster_id')
        batch_op.drop_column('active')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_current_game_id'))

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_current_team'))
        batch_op.drop_index(batch_op.f('ix_player_current_room_id'))
        batch_op.drop_index(batch_op.f('ix_player_active'))
    op.drop_table('player')

    op.drop_table('room')

    # ### end Alembic commands ###
