"""Store captains on game

Revision ID: a5b770d8f610
Revises: c1674b900fad
Create Date: 2020-04-20 22:42:37.953136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b770d8f610'
down_revision = 'c1674b900fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blue_captain_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('red_captain_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_game_blue_captain_id'), ['blue_captain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_red_captain_id'), ['red_captain_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_game_red_captain_id_player'), 'player', ['red_captain_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_game_blue_captain_id_player'), 'player', ['blue_captain_id'], ['id'])

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('captain')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('captain', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_game_blue_captain_id_player'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_game_red_captain_id_player'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_game_red_captain_id'))
        batch_op.drop_index(batch_op.f('ix_game_blue_captain_id'))
        batch_op.drop_column('red_captain_id')
        batch_op.drop_column('blue_captain_id')

    # ### end Alembic commands ###
