"""20200425 added spymaster status to players

Revision ID: a9dc26444d5c
Revises: 13accd7b360b
Create Date: 2020-04-25 17:22:21.314385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9dc26444d5c'
down_revision = '13accd7b360b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index('ix_game_blue_spymaster_id')
        batch_op.drop_index('ix_game_red_spymaster_id')
        batch_op.drop_constraint('fk_game_blue_spymaster_id_player', type_='foreignkey')
        batch_op.drop_constraint('fk_game_red_spymaster_id_player', type_='foreignkey')
        batch_op.drop_column('red_spymaster_id')
        batch_op.drop_column('blue_spymaster_id')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_spymaster', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_player_is_spymaster'), ['is_spymaster'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_is_spymaster'))
        batch_op.drop_column('is_spymaster')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blue_spymaster_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('red_spymaster_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_game_red_spymaster_id_player', 'player', ['red_spymaster_id'], ['id'])
        batch_op.create_foreign_key('fk_game_blue_spymaster_id_player', 'player', ['blue_spymaster_id'], ['id'])
        batch_op.create_index('ix_game_red_spymaster_id', ['red_spymaster_id'], unique=False)
        batch_op.create_index('ix_game_blue_spymaster_id', ['blue_spymaster_id'], unique=False)

    # ### end Alembic commands ###
