"""20200905 Included language in Word, Game and Room

Revision ID: fd953c6db722
Revises: a9dc26444d5c
Create Date: 2020-09-05 11:27:41.545592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd953c6db722'
down_revision = 'a9dc26444d5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('language_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_language'))
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_id', sa.String(length=5), nullable=True))
        batch_op.create_index(batch_op.f('ix_game_language_id'), ['language_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_game_language_id_language'), 'language', ['language_id'], ['id'])

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_id', sa.String(length=5), nullable=True))
        batch_op.create_index(batch_op.f('ix_room_language_id'), ['language_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_room_language_id_language'), 'language', ['language_id'], ['id'])

    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_id', sa.String(length=5), nullable=True))
        batch_op.create_index(batch_op.f('ix_word_language_id'), ['language_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_word_language_id_language'), 'language', ['language_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_word_language_id_language'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_word_language_id'))
        batch_op.drop_column('language_id')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_room_language_id_language'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_room_language_id'))
        batch_op.drop_column('language_id')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_game_language_id_language'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_game_language_id'))
        batch_op.drop_column('language_id')

    op.drop_table('language')
    # ### end Alembic commands ###
